name: Moodle Database Schema Generator

on:
  push:
    tags:
      - '*'

jobs:
  moodle-schema:
    strategy:
      matrix:
        moodle-branch: ['MOODLE_400_STABLE', 'MOODLE_39_STABLE']
      fail-fast: false
    runs-on: ubuntu-latest

    services:
      mariadb:
        image: mariadb:10.6
        env:
          MYSQL_ROOT_PASSWORD: a
        ports:
          - 3312:3306

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Clone Moodle Repository
        run: git clone --branch ${{ matrix.moodle-branch }} https://github.com/moodle/moodle moodle_src

      - name: Find XMLDB Files
        run: find moodle_src -name install.xml > list_of_xmldb_files.txt

      - name: Run Python Script to Convert XMLDB to SQL
        run: python3 convert_xmldb_to_create_table_statements.py > create_tables.sql

      - name: Test SQL File
        run: |
          echo "CREATE DATABASE IF NOT EXISTS diagram;" | mysql -h 127.0.0.1 -P 3312 -u root -pa
          cat create_tables.sql | mysql -h 127.0.0.1 -P 3312 -u root -pa -D diagram

      - name: Compress SQL file with xz
        run: xz -e9 create_tables.sql

      - name: Upload create_tables.sql.xz as artifact
        uses: actions/upload-artifact@v2
        with:
          name: create_moodle_tables_${{ matrix.moodle-branch }}.sql.xz
          path: create_tables.sql.xz
